@BASE_URL=http://localhost:8080

### Get User By Id
GET {{BASE_URL}}/getUserById/test

### Create User
POST {{BASE_URL}}/createUser
Content-Type: application/json

{
  "email": "teste@example.com",
  "password": "teste@123",
  "name": "Renan",
  "age": 2
}